/**
 * The bundled mineru-tools skill: what MinerU parsing is, how the two API
 * modes behave, tool usage, limits, and the activation flow.
 * @module dsh-mineru/skill
 */
export const SKILL_NAME = 'mineru-tools';

export const SKILL_DESCRIPTION = 'MinerU 多模态文档解析: PDF/Office/图片/HTML 转为结构化 Markdown. 涵盖精准解析 API 与 Agent 轻量解析 API 的调用、批量解析、结果文件与官方限制.';

export const SKILL_CONTENT = '# MinerU 文档解析 (dsh-mineru)\n\n本技能授予你基于 MinerU 的多模态全格式文档解析能力. 所有解析结果以结构化 Markdown 落地为工作区文件 (Artifact), 同时工具结果内附有限长度的预览.\n\n## 可用工具\n\n- mineru_parse — 解析单个文档 (本地文件路径或 http(s) URL).\n- mineru_batch_parse — 批量解析 (仅精准解析 API, 需要 Token; 本地文件或 URL 列表).\n- mineru_task — 查询/收集已提交任务的结果 (超时后恢复用).\n\n若上述工具未出现在你的工具列表中, 先调用一次 mineru_activate 激活本插件 (该工具在激活后对本会话隐藏).\n\n## 两种 API 模式 (自动选择, 可显式覆盖)\n\n| 维度 | 精准解析 API (需 Token) | Agent 轻量解析 API (免 Token) |\n| --- | --- | --- |\n| 触发 | 已配置 MinerU Token (默认自动) | Token 留空 (默认自动) |\n| 模型 | pipeline / vlm (默认) / MinerU-HTML | 固定 pipeline 轻量模型 |\n| 限制 | <=200MB, 单次请求 <=200 页 (工作区 PDF 超出时自动分片) | <=10MB, <=20 页 (不自动分片) |\n| 批量 | 支持 (URL <=200 个/批, 本地上传 <=50 个/批) | 仅单文件 |\n| 输出 | Zip: full.md + JSON (可加 docx/html/latex) | 仅 Markdown |\n\nmode 参数可显式指定: mode="precision" 强制精准解析 (无 Token 会报错), mode="agent" 强制轻量解析, 缺省 auto 按 Token 是否配置自动选择.\n\n## 使用要点\n\n1. 来源: 本地文件用工作区路径; 远程文档用完整 http(s) URL (注意 MinerU 无法访问 github/aws 等被墙 URL).\n2. HTML 文件仅精准解析支持, 且自动强制 model_version=MinerU-HTML. Agent 模式不支持 html/doc/ppt/xls.\n3. 页码范围: 精准解析用 pageRanges (逗号分隔, 如 "2,4-6", 支持 "2--2" 倒数页码); Agent 用 pageRange (如 "1-10"). 工作区 PDF 本次要解析的页数超过单次 200 页上限时, 插件自动按页分片提交并合并结果, 不需要新参数.\n4. language 取值: ch (中英, 默认), en, japan, korean, chinese_cht, latin, arabic, cyrillic, east_slavic, devanagari, ch_server, ta, te, ka, el, th.\n5. extraFormats 仅精准解析有效: ["docx","html","latex"] 会随 Zip 一并导出.\n6. 长文档用精准解析: 工作区 PDF 超过单次 200 页上限会自动分片并合并, 一般不必手动分段; 也可以显式传 pageRanges 只解析一部分. 大批量文档用 mineru_batch_parse (批量不按页分片).\n6b. Web 界面可直接把文档/图片拖入聊天窗口: 插件会自动保存到工作区并把文件路径填入输入框 (不自动发送), 用户补充需求后自行发送; 你收到文件路径后按第 7 条调用 mineru_parse.\n7. 结果目录: <workspace>/.dsh-mineru/artifacts/<run>/. 精准解析为解包后的完整 Zip (full.md, *_content_list.json, layout.json, images/ 等), Agent 为 full.md. 自动分片时: 运行目录根部是 full.md (按片拼接, 每段前有一行分片注释) 与 content_list.json (合并, page_idx 已映射回原文档页码); layout.json 与 <uuid>_model.json 按页数组组织, 按片保留在 chunks/chunk-<n>/ 下; 图片并入根目录 images/. 工具结果的 chunkCount/chunks 字段列出每片的页码范围、batchId、状态与耗时. 请用 read 工具读取 full.md 全文; 工具结果里的 preview 字段是截断预览.\n8. 结果文件路径同时出现在 tool/result 中, Web 界面可直接预览/打开; URL 为签名链接, 带有效期.\n8b. 需要按页码核引 (学术引用, 逐页校对) 时传 anchor=true: 精准解析会在同目录额外产出 document.md, 每块前一行 <!-- pN bK --> 标明原文档页码 (1 基) 与页内块序 (1 基, 按 content_list.json 顺序, 页眉/页脚/页码占号故可能不连续). 该产物是纯增量, 不开时 full.md 等既有产物完全不变; Agent 轻量解析没有 content_list.json, 传了只会得到一条提示.\n\n## 官方限流 (插件已内置本地限速与 429 退避)\n\n- 提交: 50 个文件/分钟 (含单文件、批量上传、批量 URL), 5000 个文件/天/用户 (html 最多 100 个/天).\n- 查询: 1000 次/分钟.\n- 超出限制的请求会被系统拒绝 (HTTP 429).\n\n## 错误处理\n\n- A0202/A0211 → Token 错误/过期, 提示用户在设置中更新 Token.\n- -60005/-30001 → 文件超限 (200MB / 10MB); -60006/-30003 → 页数超限 (200 / 20 页). 仍看到 -60006 说明本地读不出该文件的页数 (非 PDF、加密或结构异常) 或 pageRanges 写法无法在本地分片, 按提示手动分段; Agent 免 Token 路径按 IP 限流, 不做自动分片, 请改用精准解析或自行分段.\n- -60018 → 当日配额已满; 429 → 限频, 稍后重试或降低并发.\n- 超时: 任务仍在服务端, 可稍后用 mineru_task (taskId + api) 继续收集结果, 无需重新提交.\n- 传了 anchor=true 但结果是 Agent 轻量解析 (无 content_list.json) 时: 只返回一条提示且不产出 document.md, 解析本身仍然成功.';
